baseURL = "https://diyruz.github.io/"
languageCode = "en-us"
title = "DIY zigbee devices"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
disqusShortname = "diyruz"
canonifyURLs = true
googleAnalytics = "G-B6LYD00LWS"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
    site_logo = "/img/diyruz.png"
    github="https://github.com/diyruz"
    favicon = "/img/favicon.ico"
